name: Market
version: 5.0
api: 5.0.0
main: dhnnz\Market\Loader
author: dhnnz
website: https://github.com/dhnnz/Market
softdepend:
  - EconomyAPI
  - BedrockEconomy

permissions:
  market.cmd:
    default: true