name: Market
version: 0.3
api: 4.0.0
main: dhnnz\Market\Loader
author: dhnnz
website: https://github.com/dhnnz/Market
softdepend:
  - EconomyAPI
  - BedrockEconomy

permissions:
  market.cmd:
    default: true